/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin:
https://github.com/trautslab/TrautsLab-OS
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TrautsLabPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  voiceServerUrl: "http://localhost:3030",
  autoRefreshMinutes: 15,
  enableVoiceOrb: true,
  highContrastDefault: false,
  sttModelName: "faster-whisper-medium",
  ttsVoice: "es_f_locutora"
};
var TrautsLabSettingTab = class extends import_obsidian.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Configuraci\xF3n de TrautsLab OS" });
    new import_obsidian.Setting(containerEl).setName("Servidor de Voz Local (URL)").setDesc("Direcci\xF3n HTTP del microservicio de enrutamiento y s\xEDntesis de voz.").addText((text) => text.setPlaceholder("http://localhost:3030").setValue(this.plugin.settings.voiceServerUrl).onChange(async (value) => {
      this.plugin.settings.voiceServerUrl = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Intervalo de Actualizaci\xF3n de Datos").setDesc("Minutos entre cada sincronizaci\xF3n autom\xE1tica de widgets.").addSlider((slider) => slider.setLimits(5, 60, 5).setValue(this.plugin.settings.autoRefreshMinutes).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.autoRefreshMinutes = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Habilitar Voice Orb Interactivo").setDesc("Muestra el widget de micr\xF3fono interactivo en la barra lateral del Command Center.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableVoiceOrb).onChange(async (value) => {
      this.plugin.settings.enableVoiceOrb = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Voz de S\xEDntesis Kokoro TTS").setDesc("Identificador de la voz en espa\xF1ol para respuestas habladas.").addDropdown((dropdown) => dropdown.addOption("es_f_locutora", "Espa\xF1ol Femenino (Locutora Natural)").addOption("es_m_narrador", "Espa\xF1ol Masculino (Narrador)").setValue(this.plugin.settings.ttsVoice).onChange(async (value) => {
      this.plugin.settings.ttsVoice = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/view.ts
var import_obsidian2 = require("obsidian");
var TRAUTSLAB_VIEW_TYPE = "trautslab-command-center-view";
var TrautsLabView = class extends import_obsidian2.ItemView {
  plugin;
  activeTab = "overview";
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return TRAUTSLAB_VIEW_TYPE;
  }
  getDisplayText() {
    return "TrautsLab OS";
  }
  getIcon() {
    return "zap";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.classList.add("trautslab-obsidian-root");
    this.renderDashboard(container);
  }
  renderDashboard(container) {
    container.innerHTML = `
      <div class="trautslab-dashboard-wrap">
        <!-- TOPBAR -->
        <header class="trautslab-topbar">
          <div class="brand-group">
            <div class="logo-mark">\u26A1</div>
            <div class="brand-titles">
              <h2>TrautsLab <span class="accent-text">OS</span></h2>
              <span class="system-status-tag"><span class="dot-online"></span> LOCAL GPU ENGINE</span>
            </div>
          </div>
          <div class="header-metrics">
            <div class="metric-pill">
              <span class="m-icon">\u26A1</span>
              <div class="m-info"><span class="m-lbl">Tokens Hoy</span><span class="m-val">48.2k</span></div>
            </div>
            <div class="metric-pill">
              <span class="m-icon">\u{1F3AF}</span>
              <div class="m-info"><span class="m-lbl">Latencia Cach\xE9</span><span class="m-val">12ms</span></div>
            </div>
          </div>
          <div class="header-actions">
            <button id="btn-obsidian-voice" class="btn-voice-launch">\u{1F399}\uFE0F Voz 3-Tier</button>
          </div>
        </header>

        <!-- BODY -->
        <div class="trautslab-body">
          <!-- NAV TABS -->
          <nav class="trautslab-tabs">
            <button class="nav-tab active" data-tab="overview">\u{1F4CA} Overview</button>
            <button class="nav-tab" data-tab="intel">\u{1F310} Daily Intel</button>
            <button class="nav-tab" data-tab="skills">\u26A1 Skills</button>
            <button class="nav-tab" data-tab="memory">\u{1F9E0} Vault Memory</button>
          </nav>

          <!-- PANELS -->
          <main class="trautslab-content" id="trautslab-content">
            <!-- OVERVIEW -->
            <section class="panel-section active" id="tab-panel-overview">
              <div class="card-grid">
                <div class="obsidian-glass-card col-2">
                  <div class="card-head"><h3>\u{1F4C5} Agenda de Hoy</h3><span class="badge-status">En vivo</span></div>
                  <div class="timeline-box">
                    <div class="t-item"><span class="t-time">09:00 AM</span> <strong>Morning Intel Scan</strong> (Completado)</div>
                    <div class="t-item current"><span class="t-time">11:00 AM</span> <strong>Revisi\xF3n de Arquitectura TrautsLab OS</strong></div>
                    <div class="t-item"><span class="t-time">03:30 PM</span> <strong>Grabaci\xF3n Demo Asistente de Voz</strong></div>
                  </div>
                </div>

                <div class="obsidian-glass-card col-1">
                  <div class="card-head"><h3>\u26A1 Disparadores de 1-Clic</h3></div>
                  <div class="skills-launcher">
                    <button class="skill-btn-action" data-skill="morning-intel-scan">\u{1F4F0} Morning Intel</button>
                    <button class="skill-btn-action" data-skill="calendar-daily-brief">\u{1F5D3}\uFE0F Brief Agenda</button>
                    <button class="skill-btn-action" data-skill="vault-sync-indexer">\u{1F504} Re-indexar Vault</button>
                  </div>
                </div>
              </div>
            </section>

            <!-- DAILY INTEL -->
            <section class="panel-section" id="tab-panel-intel">
              <div class="card-grid">
                <div class="obsidian-glass-card col-3">
                  <div class="card-head"><h3>\u2B50 GitHub Trending & Hacker News</h3></div>
                  <ul class="intel-summary-list">
                    <li><strong>deepseek-ai/DeepSeek-V3</strong>: Modelo MoE 671B abierto con inferencia local optimizada.</li>
                    <li><strong>hexgrad/kokoro</strong>: Motor TTS ultra ligero (82M params) con locuci\xF3n natural en espa\xF1ol.</li>
                    <li><strong>Marcas de agua en Claude</strong>: Cumplimiento de est\xE1ndares de IA en EU Act.</li>
                  </ul>
                </div>
              </div>
            </section>

            <!-- SKILLS -->
            <section class="panel-section" id="tab-panel-skills">
              <div class="obsidian-glass-card">
                <div class="card-head"><h3>\u{1F4CB} Registro de Skills & Log en Vivo</h3></div>
                <div class="obsidian-exec-log" id="obsidian-exec-log">
                  <div class="log-item info">[System] TrautsLab OS Command Center inicializado en Obsidian.</div>
                  <div class="log-item ready">[Ready] Motor de Voz y Enrutador listos.</div>
                </div>
              </div>
            </section>

            <!-- MEMORY -->
            <section class="panel-section" id="tab-panel-memory">
              <div class="obsidian-glass-card">
                <div class="card-head"><h3>\u{1F9E0} Mapa de Navegaci\xF3n del Vault (Patr\xF3n Karpathy)</h3></div>
                <p>Las tablas de contenidos maestros se encuentran indexadas en <code>vault/WIKI/index.md</code>.</p>
                <div class="vault-links-preview">
                  <a class="vault-link" href="#" data-path="WIKI/index.md">\u{1F4D1} Abrir WIKI/index.md</a>
                  <a class="vault-link" href="#" data-path="AGENTS.md">\u{1F4C4} Abrir AGENTS.md</a>
                </div>
              </div>
            </section>
          </main>
        </div>

        <!-- VOICE MODAL -->
        <div id="obsidian-voice-modal" class="obsidian-voice-modal" hidden>
          <div class="voice-modal-inner">
            <button class="btn-close-modal" id="btn-close-voice-modal">&times;</button>
            <div class="modal-orb">\u{1F399}\uFE0F</div>
            <h3 id="modal-voice-title">Escuchando...</h3>
            <p id="modal-transcription" class="modal-transcription">"\xBFQu\xE9 es lo m\xE1s importante en mi agenda hoy?"</p>
            <div class="modal-tier-badge" id="modal-tier-badge">Tier 2: Cach\xE9 Instant\xE1nea</div>
            <div class="modal-response" id="modal-response">
              "Tu compromiso principal hoy es la Revisi\xF3n de Arquitectura TrautsLab OS a las 11:00 AM."
            </div>
          </div>
        </div>
      </div>
    `;
    this.attachEventListeners(container);
  }
  attachEventListeners(container) {
    const tabs = container.querySelectorAll(".nav-tab");
    const panels = container.querySelectorAll(".panel-section");
    tabs.forEach((tab) => {
      tab.addEventListener("click", () => {
        tabs.forEach((t) => t.removeClass("active"));
        panels.forEach((p) => p.removeClass("active"));
        tab.addClass("active");
        const targetTab = tab.getAttribute("data-tab");
        const targetPanel = container.querySelector(`#tab-panel-${targetTab}`);
        if (targetPanel) {
          targetPanel.addClass("active");
        }
      });
    });
    const btnVoice = container.querySelector("#btn-obsidian-voice");
    btnVoice?.addEventListener("click", () => this.openVoiceModal());
    const btnCloseModal = container.querySelector("#btn-close-voice-modal");
    btnCloseModal?.addEventListener("click", () => this.closeVoiceModal());
    const skillBtns = container.querySelectorAll(".skill-btn-action");
    skillBtns.forEach((btn) => {
      btn.addEventListener("click", async () => {
        const skillId = btn.getAttribute("data-skill");
        if (skillId) {
          await this.runSkill(skillId);
        }
      });
    });
  }
  openVoiceModal() {
    const modal = this.containerEl.querySelector("#obsidian-voice-modal");
    if (!modal) return;
    modal.removeAttribute("hidden");
    const transcriptionEl = modal.querySelector("#modal-transcription");
    const responseEl = modal.querySelector("#modal-response");
    const tierBadge = modal.querySelector("#modal-tier-badge");
    if (transcriptionEl) transcriptionEl.textContent = "Consultando agenda en cach\xE9...";
    if (responseEl) responseEl.textContent = "...";
    fetch(`${this.plugin.settings.voiceServerUrl}/api/voice/query`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query: "\xBFQu\xE9 es lo m\xE1s importante en mi agenda hoy?" })
    }).then((res) => res.json()).then((data) => {
      if (transcriptionEl) transcriptionEl.textContent = `"${data.input}"`;
      if (tierBadge) tierBadge.textContent = `${data.tier} (${data.latencies.totalMs}ms)`;
      if (responseEl) responseEl.textContent = `"${data.responsePhoneticTts}"`;
      this.logMessage(`VOICE: "${data.input}" &rarr; ${data.tier} en ${data.latencies.totalMs}ms`);
    }).catch(() => {
      if (transcriptionEl) transcriptionEl.textContent = '"\xBFQu\xE9 es lo m\xE1s importante en mi agenda hoy?"';
      if (tierBadge) tierBadge.textContent = "Tier 2: Cach\xE9 Instant\xE1nea (Local Simulado)";
      if (responseEl) responseEl.textContent = '"Tu compromiso principal hoy es la Revisi\xF3n de Arquitectura TrautsLab OS a las 11:00 AM."';
    });
  }
  closeVoiceModal() {
    const modal = this.containerEl.querySelector("#obsidian-voice-modal");
    if (modal) {
      modal.setAttribute("hidden", "");
    }
  }
  async runSkill(skillId) {
    this.logMessage(`\u26A1 EJECUTANDO SKILL: ${skillId}...`);
    setTimeout(() => {
      this.logMessage(`\u2713 Skill '${skillId}' finalizada exitosamente.`);
    }, 800);
  }
  logMessage(text) {
    const logContainer = this.containerEl.querySelector("#obsidian-exec-log");
    if (!logContainer) return;
    const line = document.createElement("div");
    line.className = "log-item info";
    line.innerHTML = `[${(/* @__PURE__ */ new Date()).toLocaleTimeString("es-ES")}] ${text}`;
    logContainer.appendChild(line);
    logContainer.scrollTop = logContainer.scrollHeight;
  }
};

// src/main.ts
var TrautsLabPlugin = class extends import_obsidian3.Plugin {
  settings = DEFAULT_SETTINGS;
  statusBarEl = null;
  async onload() {
    await this.loadSettings();
    this.registerView(
      TRAUTSLAB_VIEW_TYPE,
      (leaf) => new TrautsLabView(leaf, this)
    );
    this.addRibbonIcon("zap", "TrautsLab OS \u2014 Command Center", () => {
      this.activateView();
    });
    this.statusBarEl = this.addStatusBarItem();
    this.updateStatusBar(true);
    this.addCommand({
      id: "open-trautslab-command-center",
      name: "Abrir Command Center Dashboard",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "trigger-voice-assistant",
      name: "Activar Asistente de Voz 3-Tier",
      callback: () => {
        const view = this.getActiveCommandCenterView();
        if (view) {
          view.openVoiceModal();
        } else {
          this.activateView().then(() => {
            setTimeout(() => this.getActiveCommandCenterView()?.openVoiceModal(), 300);
          });
        }
      }
    });
    this.addCommand({
      id: "run-morning-intel",
      name: "Ejecutar Escaneo Matutino (Morning Intel)",
      callback: async () => {
        const view = this.getActiveCommandCenterView();
        if (view) {
          await view.runSkill("morning-intel-scan");
        }
      }
    });
    this.addSettingTab(new TrautsLabSettingTab(this.app, this));
    console.log("[TrautsLab OS] Plugin de Obsidian inicializado correctamente.");
  }
  onunload() {
    console.log("[TrautsLab OS] Plugin descargado.");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateStatusBar(true);
  }
  updateStatusBar(isOnline) {
    if (!this.statusBarEl) return;
    this.statusBarEl.empty();
    const dot = this.statusBarEl.createSpan({ cls: "trautslab-status-dot" });
    dot.style.display = "inline-block";
    dot.style.width = "7px";
    dot.style.height = "7px";
    dot.style.borderRadius = "50%";
    dot.style.backgroundColor = isOnline ? "#10b981" : "#ef4444";
    dot.style.marginRight = "6px";
    dot.style.boxShadow = isOnline ? "0 0 6px #10b981" : "none";
    this.statusBarEl.createSpan({ text: "TrautsLab OS (GPU)" });
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(TRAUTSLAB_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf("tab");
      if (leaf) {
        await leaf.setViewState({ type: TRAUTSLAB_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  getActiveCommandCenterView() {
    const leaves = this.app.workspace.getLeavesOfType(TRAUTSLAB_VIEW_TYPE);
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
};
module.exports = main_exports.default || main_exports;
